/**
 * AdGuard Home
 * AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API. 
 *
 * OpenAPI spec version: 0.107
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export class BlockedService {
    /**
    * The SVG icon as a Base64-encoded string to make it easier to embed it into a data URL. 
    */
    'iconSvg': string;
    /**
    * The ID of this service. 
    */
    'id': string;
    /**
    * The human-readable name of this service. 
    */
    'name': string;
    /**
    * The array of the filtering rules. 
    */
    'rules': Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "iconSvg",
            "baseName": "icon_svg",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "rules",
            "baseName": "rules",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BlockedService.attributeTypeMap;
    }

    public constructor() {
    }
}

