/**
 * AdGuard Home
 * AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API. 
 *
 * OpenAPI spec version: 0.107
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Schedule } from '../models/Schedule.js';
import { HttpFile } from '../http/http.js';

export class BlockedServicesSchedule {
    'schedule'?: Schedule;
    /**
    * The names of the blocked services. 
    */
    'ids'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "schedule",
            "baseName": "schedule",
            "type": "Schedule",
            "format": ""
        },
        {
            "name": "ids",
            "baseName": "ids",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BlockedServicesSchedule.attributeTypeMap;
    }

    public constructor() {
    }
}

