/**
 * AdGuard Home
 * AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API. 
 *
 * OpenAPI spec version: 0.107
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BlockedService } from '../models/BlockedService.js';
import { HttpFile } from '../http/http.js';

export class BlockedServicesAll {
    'blockedServices': Array<BlockedService>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "blockedServices",
            "baseName": "blocked_services",
            "type": "Array<BlockedService>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BlockedServicesAll.attributeTypeMap;
    }

    public constructor() {
    }
}

