/**
 * AdGuard Home
 * AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API. 
 *
 * OpenAPI spec version: 0.107
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export class CheckConfigRequestInfo {
    'ip'?: string;
    'port'?: number;
    'autofix'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "ip",
            "baseName": "ip",
            "type": "string",
            "format": ""
        },
        {
            "name": "port",
            "baseName": "port",
            "type": "number",
            "format": "uint16"
        },
        {
            "name": "autofix",
            "baseName": "autofix",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CheckConfigRequestInfo.attributeTypeMap;
    }

    public constructor() {
    }
}

