/**
 * AdGuard Home
 * AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API. 
 *
 * OpenAPI spec version: 0.107
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Client } from '../models/Client.js';
import { HttpFile } from '../http/http.js';

/**
* Client update request
*/
export class ClientUpdate {
    'name'?: string;
    'data'?: Client;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Client",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ClientUpdate.attributeTypeMap;
    }

    public constructor() {
    }
}

