/**
 * AdGuard Home
 * AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API. 
 *
 * OpenAPI spec version: 0.107
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SafeSearchConfig } from '../models/SafeSearchConfig.js';
import { Schedule } from '../models/Schedule.js';
import { HttpFile } from '../http/http.js';

/**
* Client information.
*/
export class Client {
    /**
    * Name
    */
    'name'?: string;
    /**
    * IP, CIDR, MAC, or ClientID.
    */
    'ids'?: Array<string>;
    'useGlobalSettings'?: boolean;
    'filteringEnabled'?: boolean;
    'parentalEnabled'?: boolean;
    'safebrowsingEnabled'?: boolean;
    'safesearchEnabled'?: boolean;
    'safeSearch'?: SafeSearchConfig;
    'useGlobalBlockedServices'?: boolean;
    'blockedServicesSchedule'?: Schedule;
    'blockedServices'?: Array<string>;
    'upstreams'?: Array<string>;
    'tags'?: Array<string>;
    /**
    * NOTE: If `ignore_querylog` is not set in HTTP API `GET /clients/add` request then default value (false) will be used.  If `ignore_querylog` is not set in HTTP API `GET /clients/update` request then the existing value will not be changed.  This behaviour can be changed in the future versions. 
    */
    'ignoreQuerylog'?: boolean;
    /**
    * NOTE: If `ignore_statistics` is not set in HTTP API `GET /clients/add` request then default value (false) will be used.  If `ignore_statistics` is not set in HTTP API `GET /clients/update` request then the existing value will not be changed.  This behaviour can be changed in the future versions. 
    */
    'ignoreStatistics'?: boolean;
    /**
    * NOTE: If `upstreams_cache_enabled` is not set in HTTP API `GET /clients/add` request then default value (false) will be used.  If `upstreams_cache_enabled` is not set in HTTP API `GET /clients/update` request then the existing value will not be changed.  This behaviour can be changed in the future versions. 
    */
    'upstreamsCacheEnabled'?: boolean;
    /**
    * NOTE: If `upstreams_cache_enabled` is not set in HTTP API `GET /clients/update` request then the existing value will not be changed.  This behaviour can be changed in the future versions. 
    */
    'upstreamsCacheSize'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "ids",
            "baseName": "ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "useGlobalSettings",
            "baseName": "use_global_settings",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "filteringEnabled",
            "baseName": "filtering_enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "parentalEnabled",
            "baseName": "parental_enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "safebrowsingEnabled",
            "baseName": "safebrowsing_enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "safesearchEnabled",
            "baseName": "safesearch_enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "safeSearch",
            "baseName": "safe_search",
            "type": "SafeSearchConfig",
            "format": ""
        },
        {
            "name": "useGlobalBlockedServices",
            "baseName": "use_global_blocked_services",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "blockedServicesSchedule",
            "baseName": "blocked_services_schedule",
            "type": "Schedule",
            "format": ""
        },
        {
            "name": "blockedServices",
            "baseName": "blocked_services",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "upstreams",
            "baseName": "upstreams",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "ignoreQuerylog",
            "baseName": "ignore_querylog",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "ignoreStatistics",
            "baseName": "ignore_statistics",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "upstreamsCacheEnabled",
            "baseName": "upstreams_cache_enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "upstreamsCacheSize",
            "baseName": "upstreams_cache_size",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Client.attributeTypeMap;
    }

    public constructor() {
    }
}

