/**
 * AdGuard Home
 * AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API. 
 *
 * OpenAPI spec version: 0.107
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Client } from '../models/Client.js';
import { ClientAuto } from '../models/ClientAuto.js';
import { HttpFile } from '../http/http.js';

export class Clients {
    /**
    * Clients array
    */
    'clients'?: Array<Client>;
    /**
    * Auto-Clients array
    */
    'autoClients'?: Array<ClientAuto>;
    'supportedTags'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "clients",
            "baseName": "clients",
            "type": "Array<Client>",
            "format": ""
        },
        {
            "name": "autoClients",
            "baseName": "auto_clients",
            "type": "Array<ClientAuto>",
            "format": ""
        },
        {
            "name": "supportedTags",
            "baseName": "supported_tags",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Clients.attributeTypeMap;
    }

    public constructor() {
    }
}

