/**
 * AdGuard Home
 * AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API. 
 *
 * OpenAPI spec version: 0.107
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export class DhcpConfigV6 {
    'rangeStart'?: string;
    'leaseDuration'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "rangeStart",
            "baseName": "range_start",
            "type": "string",
            "format": ""
        },
        {
            "name": "leaseDuration",
            "baseName": "lease_duration",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DhcpConfigV6.attributeTypeMap;
    }

    public constructor() {
    }
}

