/**
 * AdGuard Home
 * AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API. 
 *
 * OpenAPI spec version: 0.107
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DhcpSearchV4 } from '../models/DhcpSearchV4.js';
import { DhcpSearchV6 } from '../models/DhcpSearchV6.js';
import { HttpFile } from '../http/http.js';

/**
* Information about a DHCP server discovered in the current network. 
*/
export class DhcpSearchResult {
    'v4'?: DhcpSearchV4;
    'v6'?: DhcpSearchV6;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "v4",
            "baseName": "v4",
            "type": "DhcpSearchV4",
            "format": ""
        },
        {
            "name": "v6",
            "baseName": "v6",
            "type": "DhcpSearchV6",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DhcpSearchResult.attributeTypeMap;
    }

    public constructor() {
    }
}

