/**
 * AdGuard Home
 * AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API. 
 *
 * OpenAPI spec version: 0.107
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export class DhcpSearchResultOtherServer {
    /**
    * The result of searching the other DHCP server. 
    */
    'found'?: DhcpSearchResultOtherServerFoundEnum;
    /**
    * Set if found=error
    */
    'error'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "found",
            "baseName": "found",
            "type": "DhcpSearchResultOtherServerFoundEnum",
            "format": ""
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DhcpSearchResultOtherServer.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum DhcpSearchResultOtherServerFoundEnum {
    Yes = 'yes',
    No = 'no',
    Error = 'error'
}

