/**
 * AdGuard Home
 * AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API. 
 *
 * OpenAPI spec version: 0.107
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DhcpSearchResultOtherServer } from '../models/DhcpSearchResultOtherServer.js';
import { HttpFile } from '../http/http.js';

export class DhcpSearchV6 {
    'otherServer'?: DhcpSearchResultOtherServer;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "otherServer",
            "baseName": "other_server",
            "type": "DhcpSearchResultOtherServer",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DhcpSearchV6.attributeTypeMap;
    }

    public constructor() {
    }
}

