/**
 * AdGuard Home
 * AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API. 
 *
 * OpenAPI spec version: 0.107
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Filter } from '../models/Filter.js';
import { HttpFile } from '../http/http.js';

/**
* Filtering settings
*/
export class FilterStatus {
    'enabled'?: boolean;
    'interval'?: number;
    'filters'?: Array<Filter>;
    'whitelistFilters'?: Array<Filter>;
    'userRules'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "interval",
            "baseName": "interval",
            "type": "number",
            "format": ""
        },
        {
            "name": "filters",
            "baseName": "filters",
            "type": "Array<Filter>",
            "format": ""
        },
        {
            "name": "whitelistFilters",
            "baseName": "whitelist_filters",
            "type": "Array<Filter>",
            "format": ""
        },
        {
            "name": "userRules",
            "baseName": "user_rules",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FilterStatus.attributeTypeMap;
    }

    public constructor() {
    }
}

