/**
 * AdGuard Home
 * AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API. 
 *
 * OpenAPI spec version: 0.107
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

/**
* Statistics configuration
*/
export class GetStatsConfigResponse {
    /**
    * Are statistics enabled
    */
    'enabled': boolean;
    /**
    * Statistics rotation interval in milliseconds
    */
    'interval': number;
    /**
    * List of host names, which should not be counted
    */
    'ignored': Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "interval",
            "baseName": "interval",
            "type": "number",
            "format": ""
        },
        {
            "name": "ignored",
            "baseName": "ignored",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetStatsConfigResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

