/**
 * AdGuard Home
 * AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API. 
 *
 * OpenAPI spec version: 0.107
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

/**
* /version.json request data
*/
export class GetVersionRequest {
    /**
    * If false, server will check for a new version data only once in several hours. 
    */
    'recheckNow'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "recheckNow",
            "baseName": "recheck_now",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetVersionRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

