/**
 * AdGuard Home
 * AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API. 
 *
 * OpenAPI spec version: 0.107
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AddressInfo } from '../models/AddressInfo.js';
import { HttpFile } from '../http/http.js';

/**
* AdGuard Home initial configuration for the first-install wizard. 
*/
export class InitialConfiguration {
    'dns': AddressInfo;
    'web': AddressInfo;
    /**
    * Basic auth username
    */
    'username': string;
    /**
    * Basic auth password
    */
    'password': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dns",
            "baseName": "dns",
            "type": "AddressInfo",
            "format": ""
        },
        {
            "name": "web",
            "baseName": "web",
            "type": "AddressInfo",
            "format": ""
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string",
            "format": ""
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InitialConfiguration.attributeTypeMap;
    }

    public constructor() {
    }
}

