/**
 * AdGuard Home
 * AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API. 
 *
 * OpenAPI spec version: 0.107
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

/**
* Network interface info
*/
export class NetInterface {
    /**
    * Flags could be any combination of the following values, divided by the \"|\" character: \"up\", \"broadcast\", \"loopback\", \"pointtopoint\" and \"multicast\". 
    */
    'flags': string;
    'hardwareAddress': string;
    'name': string;
    'ipAddresses'?: Array<string>;
    'mtu': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "flags",
            "baseName": "flags",
            "type": "string",
            "format": ""
        },
        {
            "name": "hardwareAddress",
            "baseName": "hardware_address",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "ipAddresses",
            "baseName": "ip_addresses",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "mtu",
            "baseName": "mtu",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NetInterface.attributeTypeMap;
    }

    public constructor() {
    }
}

