/**
 * AdGuard Home
 * AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API. 
 *
 * OpenAPI spec version: 0.107
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

/**
* Information about the current user
*/
export class ProfileInfo {
    'name': string;
    'language': string;
    /**
    * Interface theme
    */
    'theme': ProfileInfoThemeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "string",
            "format": ""
        },
        {
            "name": "theme",
            "baseName": "theme",
            "type": "ProfileInfoThemeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProfileInfo.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum ProfileInfoThemeEnum {
    Auto = 'auto',
    Dark = 'dark',
    Light = 'light'
}

