/**
 * AdGuard Home
 * AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API. 
 *
 * OpenAPI spec version: 0.107
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

/**
* Client WHOIS information, if any. 
*/
export class QueryLogItemClientWhois {
    /**
    * City, if any. 
    */
    'city'?: string;
    /**
    * Country, if any. 
    */
    'country'?: string;
    /**
    * Organization name, if any. 
    */
    'orgname'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "city",
            "baseName": "city",
            "type": "string",
            "format": ""
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string",
            "format": ""
        },
        {
            "name": "orgname",
            "baseName": "orgname",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return QueryLogItemClientWhois.attributeTypeMap;
    }

    public constructor() {
    }
}

