/**
 * AdGuard Home
 * AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API. 
 *
 * OpenAPI spec version: 0.107
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { QueryLogItem } from '../models/QueryLogItem.js';
import { HttpFile } from '../http/http.js';

/**
* Query log
*/
export class QueryLog {
    'oldest'?: string;
    'data'?: Array<QueryLogItem>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "oldest",
            "baseName": "oldest",
            "type": "string",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<QueryLogItem>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return QueryLog.attributeTypeMap;
    }

    public constructor() {
    }
}

