/**
 * AdGuard Home
 * AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API. 
 *
 * OpenAPI spec version: 0.107
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

/**
* Query log configuration
*/
export class QueryLogConfig {
    /**
    * Is query log enabled
    */
    'enabled'?: boolean;
    /**
    * Time period for query log rotation. 
    */
    'interval'?: QueryLogConfigIntervalEnum;
    /**
    * Anonymize clients\' IP addresses
    */
    'anonymizeClientIp'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "interval",
            "baseName": "interval",
            "type": "QueryLogConfigIntervalEnum",
            "format": ""
        },
        {
            "name": "anonymizeClientIp",
            "baseName": "anonymize_client_ip",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return QueryLogConfig.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum QueryLogConfigIntervalEnum {
    NUMBER_0_DOT_25 = 0.25,
    NUMBER_1 = 1,
    NUMBER_7 = 7,
    NUMBER_30 = 30,
    NUMBER_90 = 90
}

