/**
 * AdGuard Home
 * AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API. 
 *
 * OpenAPI spec version: 0.107
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

/**
* Applied rule.
*/
export class ResultRule {
    /**
    * In case if there\'s a rule applied to this DNS request, this is ID of the filter list that the rule belongs to. 
    */
    'filterListId'?: number;
    /**
    * The text of the filtering rule applied to the request (if any). 
    */
    'text'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "filterListId",
            "baseName": "filter_list_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ResultRule.attributeTypeMap;
    }

    public constructor() {
    }
}

