/**
 * AdGuard Home
 * AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API. 
 *
 * OpenAPI spec version: 0.107
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RewriteEntry } from '../models/RewriteEntry.js';
import { HttpFile } from '../http/http.js';

/**
* Rewrite rule update object
*/
export class RewriteUpdate {
    'target'?: RewriteEntry;
    'update'?: RewriteEntry;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "target",
            "baseName": "target",
            "type": "RewriteEntry",
            "format": ""
        },
        {
            "name": "update",
            "baseName": "update",
            "type": "RewriteEntry",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RewriteUpdate.attributeTypeMap;
    }

    public constructor() {
    }
}

