/**
 * AdGuard Home
 * AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API. 
 *
 * OpenAPI spec version: 0.107
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

/**
* AdGuard Home server status and configuration
*/
export class ServerStatus {
    'dnsAddresses': Array<string>;
    'dnsPort': number;
    'httpPort': number;
    'protectionEnabled': boolean;
    'protectionDisabledDuration'?: number;
    'dhcpAvailable'?: boolean;
    'running': boolean;
    'version': string;
    'language': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dnsAddresses",
            "baseName": "dns_addresses",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "dnsPort",
            "baseName": "dns_port",
            "type": "number",
            "format": "uint16"
        },
        {
            "name": "httpPort",
            "baseName": "http_port",
            "type": "number",
            "format": "uint16"
        },
        {
            "name": "protectionEnabled",
            "baseName": "protection_enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "protectionDisabledDuration",
            "baseName": "protection_disabled_duration",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "dhcpAvailable",
            "baseName": "dhcp_available",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "running",
            "baseName": "running",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ServerStatus.attributeTypeMap;
    }

    public constructor() {
    }
}

