/**
 * AdGuard Home
 * AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API. 
 *
 * OpenAPI spec version: 0.107
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

/**
* Upstream configuration to be tested
*/
export class UpstreamsConfig {
    /**
    * Bootstrap DNS servers, port is optional after colon. 
    */
    'bootstrapDns': Array<string>;
    /**
    * Upstream DNS servers, port is optional after colon. 
    */
    'upstreamDns': Array<string>;
    /**
    * Fallback DNS servers, port is optional after colon. 
    */
    'fallbackDns'?: Array<string>;
    /**
    * Local PTR resolvers, port is optional after colon. 
    */
    'privateUpstream'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "bootstrapDns",
            "baseName": "bootstrap_dns",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "upstreamDns",
            "baseName": "upstream_dns",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "fallbackDns",
            "baseName": "fallback_dns",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "privateUpstream",
            "baseName": "private_upstream",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpstreamsConfig.attributeTypeMap;
    }

    public constructor() {
    }
}

