/**
 * AdGuard Home
 * AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API. 
 *
 * OpenAPI spec version: 0.107
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

/**
* Information about the latest available version of AdGuard Home. 
*/
export class VersionInfo {
    /**
    * If true then other fields doesn\'t appear. 
    */
    'disabled': boolean;
    'newVersion'?: string;
    'announcement'?: string;
    'announcementUrl'?: string;
    'canAutoupdate'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "disabled",
            "baseName": "disabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "newVersion",
            "baseName": "new_version",
            "type": "string",
            "format": ""
        },
        {
            "name": "announcement",
            "baseName": "announcement",
            "type": "string",
            "format": ""
        },
        {
            "name": "announcementUrl",
            "baseName": "announcement_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "canAutoupdate",
            "baseName": "can_autoupdate",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VersionInfo.attributeTypeMap;
    }

    public constructor() {
    }
}

